### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by paride** [google/fscryptctl#12]
Hello @josephlr, I'd like to package `fscryptctl` for Debian, but normally only released (tagged) versions are packaged. Do you plan to tag a release anytime soon? Thank you.

**Comment by comio** [comment]
I'm also waiting for a tagged version.

Thanks and ciao

luigi

**Comment by josephlr** [comment]
Version `v0.1` has been tagged. It's just the last commit that included support for V1 encryption policies.

Version `v1.0` is about to be released. It will include #16, which removes V1 policy support and adds V2 policy support.

I would recommend packaging `v1.0` when it is released.
