### ISSUE TITLE
Usage example incomplete

### ISSUE THREAD

**Issue by pepa65** [google/fscryptctl#13]
I found the usage example in `README.md` very helpful in illustrating the usage. But when I came to `umount` I was lost, as there wasn't an earlier corresponding mount nor an explanation of its role. I am guessing this is a workaround for doing drop_cache without privilege escalation. What would the earlier missing mount command look like in the given usage example?

**Comment by josephlr** [comment]
We've updated the README.md to include this information (as well as fixing up a bunch of other documentation issues). Please reopen this issue if you still find any parts to be unclear.
