### ISSUE TITLE
In fscryptctl user space, after removing the key from key ring, the encrypted directories file names continues to be in clear form.

### ISSUE THREAD

**Issue by pandiaraj88** [google/fscryptctl#34]
I am using fscrypt kernel space and fscryptctl at user space to make use of the fscrypt encryption tool.
I have encrypted a directory using add_key -> set_policy->created valid data files under the encryption directory.
Before I remove the key, I have confirmed the open files of the directory is closed properly.
Now, if I remove the key from the key ring, the file names of the encrypted directory continues to be in clear form. The file names are change to encrypted form only if I reboot the system or if I dorp the cache/inode using the system echo 2 >/proc/sys/vm/drop_caches.

fscryptctl version: v1.0.0-6-gab54426

Is there a way to handle this neatly and make the file names as encrypted name upon removing the key from kernel key ring? I do not wish to drop the entire system caches
I have tried this on both Ubuntu machine and my customised embedded system as well. The observation is same.

**Comment by ebiggers** [comment]
When you say "remove the key from the key ring", are you using `fscryptctl remove_key`?

**Comment by pandiaraj88** [comment]
Yes,

**Comment by pandiaraj88** [comment]
Hi,
I have tried the above said point 3(To avoid this you need to pass it the path to the filesystem's mountpoint, not the path to the encrypted directory).
Experiment carried:
I have created dir1 and added the encryption key to this directory. <fscryptctl add_key dir1 <key.bin>
Inside dir1, dir2 is created and the policy is applied. <fscryptctl set_policy key_id dir1/dir2>
Created data files in dir2. <echo "data" >dir1/dir2/file.txt>
Removed the key applied on dir1. <fscryptctl remove_key key_id dir1>
**Observation**:
       Still I see the same warning message (warning: some files using this key are still in-use) and file names are continue to be in clear form.

But the same experiment **is making the file names listed encrypted properly if I try it on block device node mount point**(/dev/sda is mounted on dir1).

This shows that, with in the system(without andy device mount point), If we make use of this fscrypt encryption, the file name encryption is not  getting applied properly due to some reference in the backend.?

On this situation, further when I try to drop the system inode cache(echo 2 >/proc/sys/vm/drop_caches), Immediately the file names are appear in encrypted form. 

Is there a clean way, where we can drop the inode cache specific to this directory before removing the keys are any better suggestion on this context.

**Comment by ebiggers** [comment]
It works for me.

```                                             
mkfs.ext4 -O encrypt -F /dev/vdb                                                 
mount /dev/vdb /mnt                                                              
keyid=$(head -c 64 /dev/urandom | fscryptctl add_key /mnt)                       
mkdir -p /mnt/dir1/dir2                                                             
fscryptctl set_policy $keyid /mnt/dir1/dir2                                      
echo 'data' > /mnt/dir1/dir2/file.txt                                            
fscryptctl remove_key $keyid /mnt                                                                                                                   
```

Then:
```
$ find /mnt
/mnt
/mnt/lost+found
/mnt/dir1
/mnt/dir1/dir2
/mnt/dir1/dir2/sF5B40GuEFx992lvcp9Oy6VIctcvytX22kpeec5jU4UfWJTmjJbIYg
```

If something is not working as expected then please give the **full** series of commands you are using.

I would guess that you still are accidentally calling `remove_key` on one of the encrypted files or directories.

Remember that `add_key` and `remove_key` operate on the whole filesystem, not on individual files or directories.  So they generally should be executed on the filesystem's top-level directory.

**Comment by pandiaraj88** [comment]
Same example stated above, is working fine for me. I am clear that if we use encryption and decryption at fileystem level the file names are listed encrypted manner instantly. My use case is different and is stated below,

What I understood is that fscrypt supports encryption/decryption at directory level. In same filesystem multiple directories can be encrypted with different policies and keys.
**This directory level encryption use case also working fine for me, other than making the file names look encrypted.**

Example:
process1 will create enc_dir1 & key1.bin and apply policy on thisenc_dir1 directory, and secure his content on this directory.
process2 will create enc_dir2 & key2.bin and apply policy to enc_dir2 and secure **its content on the same filesystem** 
This continues for rest of the process as well.

**For this reason, instead of applying the key on the mount point, I am directly applying on the encryption directory itself.**
This what not encrypting the file name and displays in clear form.

```
# ls -l
total 0
# dd if=/dev/urandom of=key.bin count=64 bs=1
64+0 records in
64+0 records out
64 bytes copied, 0.000523435 s, 122 kB/s
# ll
total 12
drwxr-xr-x  2 root      root      4096 Nov 23 00:37 ./
drwxr-xr-x 18 pandiaraj pandiaraj 4096 Nov 23 00:35 ../
-rw-r--r--  1 root      root        64 Nov 23 00:37 key.bin
# mkdir process1_persistent_storage
# ls -l
total 8
-rw-r--r-- 1 root root   64 Nov 23 00:37 key.bin
drwxr-xr-x 3 root root 4096 Nov 23 00:37 process1_persistent_storage
# fscryptctl add_key process1_persistent_storage/ <key.bin 
402385bfeda297569813e18f78ded076
# mkdir process1_persistent_storage/secure_storage
# ls -l process1_persistent_storage/
total 4
drwxr-xr-x 2 root root 4096 Nov 23 00:37 secure_storage
# fscryptctl set_policy 402385bfeda297569813e18f78ded076 process1_persistent_storage/secure_storage
# echo "data" > process1_persistent_storage/secure_storage/file.txt
# fscryptctl remove_key 402385bfeda297569813e18f78ded076 process1_persistent_storage/
**warning: some files using this key are still in-use**
# ls -l process1_persistent_storage/secure_storage/
total 4
-rw-r--r-- 1 root root 5 Nov 23 00:39 file.txt

```

**Comment by ebiggers** [comment]
To re-iterate, `add_key` and `remove_key` operate on the whole filesystem, not on individual files or directories. So they generally should be executed on the filesystem's top-level directory.  Adding/removing keys has nothing to do with whether individual files or directories are encrypted or not.  That's what `set_policy` is for.

Anyway, the commands you gave don't execute `remove_key` on an encrypted directory anyway, so there should be no issue.

I tested them and there is indeed no issue.

Maybe you are running some third-party software daemon that is scanning the files as soon as they are created?

**Comment by pandiaraj88** [comment]
I cross verified my machine for any kind of scanners and didn't see anything as such. I could see apparmor active and  even I have disabled that and tried the same commands given by me above. But unfortunately the file names are still in clear form. 

I think the kernel reference to the remove_key directory inode is something I have to understand. Other than that, I do not see any reference to any of the file, directories or inodes of the encryption directory from userspace context.

**Comment by ebiggers** [comment]
First, filenames in an encrypted directory are always encrypted (on-disk).  When you write "encrypting the file names" you really mean "locking the directory".  One of the consequences of locking the directory is that the filenames in it will be listed in no-key form.

Second, yes I tried the commands you gave, and I did not see the problem.

If you could specify the filesystem type (e.g. ext4) and kernel version (e.g. v6.0) you are using, I could re-run the test with that exact filesystem type and kernel version as well, just in case there is a kernel bug.

I also notice that your example commands are storing the encryption key on the same filesystem as the encrypted files.  That destroys any security properties that the encryption has.

Maybe you should take a step back and reconsider whether filesystem encryption is actually the right solution for whatever problem you are trying to solve?  And if it is, are you sure you want to use the low-level `fscryptctl` tool instead of the higher level [`fscrypt`](https://github.com/google/fscrypt) tool?

**Comment by pandiaraj88** [comment]
Hi,
Thanks for the details. We are using ext4 filesystem and kernel version 5.10.52-v7. 
Our use case is that, this solution will be used at embedded devices, and with in single filesystem, multiple processes stores their secure data, using different keys at different encrypted directories. 
Because of embedded device use case we didn't prefer to use the fscrypt user space application which again go lang package.

Also to make the master key process & Device specific, we are generating new master key at kernel space, from the fscryptctl user space input key, uid of the process, and other device specific params. This will be used on FS_IOC_ADD_ENCRYPTION_KEY call input.

**Comment by ebiggers** [comment]
> Also to make the master key process & Device specific, we are generating new master key at kernel space, from the fscryptctl user space input key, uid of the process, nonce and other device specific params. This will be used on FS_IOC_ADD_ENCRYPTION_KEY call input.

So you have patched the filesystem encryption code in your kernel, with code that isn't upstream.

We can't support you then, as you might have broken arbitrary things.
