### ISSUE TITLE
Error when unlocking filesystem.

### ISSUE THREAD

**Issue by hamiltonp** [google/fscryptctl#4]
I tested fscrypt with ext4, but I got this error:

_root@pc1:/home/hamiltonp/Temp# fscrypt unlock mount/blah/
Enter custom passphrase for protector "test": 
**fscrypt unlock: permission denied: system error: could not insert key into the keyring**_

It persisted with password and keyfile method.

**Comment by josephlr** [comment]
Thanks for the report. Looks like this is for [fscrypt](github.com/google/fscrypt) not fscryptctl. I'm going to reopen it there
